{% set name = "tardigrade_vector_tools" %}
{% set version = "0.8.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/UCBoulder/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: ba24dcf6d1cf60cf3e851629588334556aef16c372d3cb634aaed69d2bba7e36

build:
  number: 3
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script:
    - set -x
    # Build and install c++ libraries
    - cmake -S . -B build -DCMAKE_BUILD_TYPE=Release ${CMAKE_ARGS}  # ``${CMAKE_ARGS}`` required by conda-forge recipe
    - cmake --install build --prefix ${PREFIX}
  skip: true  # [win]

requirements:
  build:
    - python
    - {{ compiler('c') }}  # TODO: Remove when upstream project CMakeLists.txt file sets ``LANGUAGE CXX``
    - {{ stdlib('c') }}  # Required by conda-forge recipe, but not upstream recipe
    - {{ compiler('cxx') }}
    - make
    - cmake >=3.30
    - tardigrade_error_tools >=0.7
    - breathe >=4.3.0
    - doxygen
    - libboost-python-devel >=1.82
    - setuptools >=62
    - setuptools_scm >=6.2
    - sphinx >=3.0.4
    - sphinx_rtd_theme >=0.4.3
    - sphinxcontrib-bibtex
    - tardigrade_error_tools >=0.9.7
  host:
    - setuptools_scm >=6.2  # TODO: Remove when upstream project CMakeLists.txt file prefers $BUILD_PREFIX/python
    - eigen >=3.3.7
    - tardigrade_error_tools >=0.9.7
  run:
    - eigen >=3.3.7
    - tardigrade_error_tools >=0.9.7

test:
  requires:
    - {{ compiler('cxx') }}
    - make
    - cmake >=3.30
    - libboost-python-devel >=1.82
    - doxygen
    - sphinx >=3.0.4
  source_files:
    - CMakeLists.txt
    - src/cpp/tests/CMakeLists.txt
    - src/cpp/tests/test_tardigrade_vector_tools.cpp
    - src/cpp/tests/test_tardigrade_interp_ndCartesian.cpp
  commands:
    - set -x
    - cmake -S . -B build -DCMAKE_BUILD_TYPE=conda-test -DCMAKE_INSTALL_LIBDIR=lib
    - cmake --build build --verbose --parallel 4
    - ctest --test-dir build --output-on-failure -R 'test_' --parallel 4

about:
  home: https://github.com/UCBoulder/tardigrade_vector_tools
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'A collection of tools for vector manipulation'
  description: |
    tardigrade-vector-tools A collection of tools for C++ that make interfacing with vectors easier
    and less prone to error. These tools also allow the user access to the powerful Eigen library which provides matrix
    utilities in such a way that Eigen does not need to be used explicitly in the user's code.
  dev_url: https://github.com/UCBoulder/tardigrade_vector_tools

extra:
  recipe-maintainers:
    - NateAM
    - kbrindley
